// app/pages/settings.vue
<script setup lang="ts">
import type { Mapping, TestResult } from '../../shared/types'
import { apiErrorMessage } from '../../shared/errors'

const store = useSettingsStore()
const status = useStatusStore()
const toast = useToast()

await store.fetch()

onMounted(() => {
  status.start()
  store.fetchTautulliUsers().catch(() => {})
})
onBeforeUnmount(() => status.stop())

const TRIGGERS = [
  { key: 'watched', label: 'Watched', recommended: true },
  { key: 'play', label: 'Play' },
  { key: 'stop', label: 'Stop' },
  { key: 'pause', label: 'Pause' },
  { key: 'resume', label: 'Resume' },
]
const selectedTriggers = ref<string[]>(['watched'])

function isTriggerSelected(key: string) {
  return selectedTriggers.value.includes(key)
}

// UCheckbox has no built-in array-group mode outside UCheckboxGroup, so a
// shared v-model across sibling checkboxes would fight itself. Each checkbox
// derives its own checked state from the array and toggles membership.
function toggleTrigger(key: string, checked: boolean) {
  if (checked) {
    if (!selectedTriggers.value.includes(key)) selectedTriggers.value.push(key)
  } else {
    selectedTriggers.value = selectedTriggers.value.filter((k) => k !== key)
  }
}

const saving = ref(false)
const syncing = ref(false)
const newUser = ref('')
const newToken = ref('')
const edit = ref<Mapping | null>(null)
const advanced = ref(false)
const manual = ref(false)
const testPanel = ref(false)

const TEST_ACTIONS = ['watched', 'play', 'stop', 'pause', 'resume']
const testRatingKey = ref('')
const testUsername = ref('')
const testAction = ref('watched')
const previewBusy = ref(false)
const sendBusy = ref(false)
const testResult = ref<TestResult | null>(null)

const mappedUsernames = computed(() => store.mappings.map((m) => m.username))

const testResultPayload = computed(() =>
  testResult.value?.payload ? JSON.stringify(testResult.value.payload, null, 2) : '',
)

const webhookUrl = computed(() => {
  const base = (store.settings?.bridge_url || window.location.origin).replace(/\/+$/, '')
  return `${base}/api/webhook/tautulli`
})

const availableUsers = computed(() => {
  const taken = new Set(store.mappings.map((m) => m.username.toLowerCase()))
  return store.tautulliUsers.filter((u) => !taken.has(u.toLowerCase()))
})

function syncSummary(m: Mapping) {
  if (m.sync_episodes && m.sync_movies) return 'TV + Movies'
  if (m.sync_episodes) return 'TV only'
  if (m.sync_movies) return 'Movies only'
  return 'nothing selected'
}

async function saveConnection() {
  saving.value = true
  try {
    await store.save({
      tautulli_url: store.settings!.tautulli_url,
      tautulli_apikey: store.settings!.tautulli_apikey,
    })
    toast.add({ title: 'Saved.', color: 'success' })
    status.refresh()
    store.fetchTautulliUsers().catch(() => {})
  } catch (e) {
    toast.add({ title: apiErrorMessage(e, 'Could not save.'), color: 'error' })
  } finally {
    saving.value = false
  }
}

async function testConnection() {
  const r = await store.testTautulli({
    tautulli_url: store.settings!.tautulli_url,
    tautulli_apikey: store.settings!.tautulli_apikey,
  })
  toast.add({ title: r.message, color: r.ok ? 'success' : 'error' })
}

async function addMapping() {
  if (!newUser.value.trim() || !newToken.value.trim()) {
    toast.add({ title: 'Username and token are both required.', color: 'error' })
    return
  }
  try {
    await store.saveMapping({ username: newUser.value.trim(), seenr_token: newToken.value.trim() })
    newUser.value = ''
    newToken.value = ''
    toast.add({ title: 'User mapped.', color: 'success' })
  } catch (e) {
    toast.add({ title: apiErrorMessage(e, 'Could not add user.'), color: 'error' })
  }
}

async function saveEdit() {
  if (!edit.value) return
  await store.saveMapping({
    username: edit.value.username,
    seenr_token: edit.value.seenr_token,
    enabled: edit.value.enabled,
    sync_movies: edit.value.sync_movies,
    sync_episodes: edit.value.sync_episodes,
  })
  edit.value = null
  toast.add({ title: 'Updated.', color: 'success' })
}

async function removeEdit() {
  if (!edit.value) return
  await store.removeMapping(edit.value.id)
  edit.value = null
  toast.add({ title: 'Removed.', color: 'success' })
}

async function runSync() {
  syncing.value = true
  try {
    const r = await store.syncWebhook(selectedTriggers.value)
    toast.add({
      title: r.created ? 'Webhook created in Tautulli.' : 'Webhook updated in Tautulli.',
      color: 'success',
    })
    status.refresh()
  } catch (e) {
    toast.add({ title: apiErrorMessage(e, 'Sync failed.'), color: 'error' })
  } finally {
    syncing.value = false
  }
}

async function saveAdvanced() {
  await store.save({
    forward_enabled: store.settings!.forward_enabled,
    seenr_base_url: store.settings!.seenr_base_url,
    bridge_url: store.settings!.bridge_url,
  })
  toast.add({ title: 'Saved.', color: 'success' })
}

// Preview and Send share this — the only difference is dryRun (build the
// payload without forwarding, vs. actually posting to seenr and recording an
// event row). Both hit the authed /api/test endpoint directly since the
// result is page-local scratch state, not shared app state like settings.
async function runTest(dryRun: boolean) {
  if (!testRatingKey.value.trim() || !testUsername.value.trim()) {
    toast.add({ title: 'rating_key and username are both required.', color: 'error' })
    return
  }
  const busy = dryRun ? previewBusy : sendBusy
  busy.value = true
  try {
    testResult.value = await $fetch<TestResult>('/api/test', {
      method: 'POST',
      body: {
        rating_key: testRatingKey.value.trim(),
        username: testUsername.value.trim(),
        action: testAction.value,
        dryRun,
      },
    })
  } catch (e) {
    toast.add({ title: apiErrorMessage(e, 'Test failed.'), color: 'error' })
  } finally {
    busy.value = false
  }
}
</script>

<template>
  <div v-if="store.settings" class="space-y-4">
    <!-- "Setup" on the left, the live status line on the right — the old page
         header. Both wrap rather than overflowing on narrow screens. -->
    <div class="flex flex-wrap items-center justify-between gap-3">
      <h2 class="text-lg font-semibold text-highlighted">Setup</h2>
      <div class="flex flex-wrap items-center gap-x-4 gap-y-1 text-xs">
        <span class="flex items-center gap-1.5">
          <span
            class="size-1.5 rounded-full"
            :class="status.tautulli === null ? 'bg-neutral-500' : status.tautulli.ok ? 'bg-success' : 'bg-error'"
          />
          <span class="text-muted">
            {{ status.tautulli === null ? 'checking…' : status.tautulli.ok ? 'Tautulli connected' : 'Tautulli offline' }}
          </span>
        </span>
        <span class="text-dimmed">{{ status.users }} {{ status.users === 1 ? 'user' : 'users' }}</span>
        <span class="flex items-center gap-1.5">
          <span class="size-1.5 rounded-full" :class="status.webhook ? 'bg-success' : 'bg-error'" />
          <span class="text-muted">{{ status.webhook ? 'webhook active' : 'no webhook' }}</span>
        </span>
      </div>
    </div>

    <SetupStep :n="1" title="Connect Tautulli" hint="where the bridge reads episode IDs">
      <div class="grid gap-4 sm:grid-cols-2">
        <UFormField label="Tautulli URL" help="e.g. http://tautulli:8181">
          <UInput v-model="store.settings.tautulli_url" placeholder="http://tautulli:8181" class="w-full" />
        </UFormField>
        <UFormField label="API key" help="Tautulli → Settings → Web Interface → API key">
          <UInput v-model="store.settings.tautulli_apikey" type="password" placeholder="xxxxxxxx" class="w-full" />
        </UFormField>
      </div>
      <div class="mt-4 flex flex-wrap gap-3">
        <UButton color="neutral" variant="subtle" label="Test connection" class="min-h-11" @click="testConnection" />
        <UButton :loading="saving" label="Save" class="min-h-11" @click="saveConnection" />
      </div>
    </SetupStep>

    <SetupStep :n="2" title="Map users to seenr" hint="each Plex user → their seenr token">
      <div class="space-y-2">
        <p v-if="!store.mappings.length" class="text-sm text-muted">No users yet. Add one below.</p>

        <!-- Stacks below sm so the Configure button never squeezes the token. -->
        <div
          v-for="m in store.mappings"
          :key="m.id"
          class="flex flex-col gap-2 rounded-lg bg-default px-3 py-2.5 ring-1 ring-default sm:flex-row sm:items-center sm:gap-3"
        >
          <div class="min-w-0 flex-1">
            <div class="flex items-center gap-2 text-sm font-medium text-highlighted">
              <span class="truncate">{{ m.username }}</span>
              <UBadge v-if="!m.enabled" color="neutral" variant="subtle" size="sm" label="paused" />
            </div>
            <div class="mt-0.5 flex flex-wrap items-center gap-x-2 text-xs text-dimmed">
              <span class="font-mono">{{ m.seenr_token.slice(0, 8) }}…{{ m.seenr_token.slice(-6) }}</span>
              <span>·</span>
              <span>{{ syncSummary(m) }}</span>
            </div>
          </div>
          <UButton
            color="neutral"
            variant="subtle"
            label="Configure"
            class="min-h-11 self-start sm:self-auto"
            @click="edit = { ...m }"
          />
        </div>
      </div>

      <!-- items-start (not items-end): the token field's help text below its
           input makes that cell taller than the plain username field, so
           bottom-aligning would misalign the inputs. Top-aligning keeps the
           inputs level since both labels are the same height. -->
      <div class="mt-4 grid gap-3 sm:grid-cols-[1fr_2fr_auto] sm:items-start">
        <UFormField label="Plex username">
          <!-- Free text still allowed, so manual entry works when Tautulli
               is unreachable. Selecting the generated "Create …" option calls
               preventDefault() internally (see SelectMenu.vue) and only emits
               `create` — it does not update v-model on its own — so the typed
               value is applied here explicitly. -->
          <USelectMenu
            v-model="newUser"
            :items="availableUsers"
            create-item
            placeholder="Select or type…"
            class="w-full"
            @create="(item) => { newUser = item }"
          />
        </UFormField>
        <UFormField label="seenr token" help="the part after /scrobble/plex/ in your seenr URL">
          <UInput v-model="newToken" placeholder="9%7CyourSeenrToken" class="w-full" />
        </UFormField>
        <div>
          <!-- The Add button has no label of its own, so with the row now
               top-aligned it would sit level with the labels above, not the
               inputs. This invisible spacer reproduces a label's height plus
               the label-to-input gap (mirroring UFormField's own
               labelWrapper + `mt-1` container spacing) purely to push the
               button down to input level. See git show 2e675ca for the
               pre-conversion React version, which used the same trick. -->
          <div class="text-sm font-medium select-none" aria-hidden="true">&nbsp;</div>
          <UButton label="Add" class="mt-1 min-h-11 w-full sm:w-auto" @click="addMapping" />
        </div>
      </div>
    </SetupStep>

    <SetupStep :n="3" title="Send Tautulli's events here" hint="one webhook, covers every user">
      <div class="mb-4">
        <div class="mb-2.5 text-sm font-medium">Triggers to enable</div>
        <div class="flex flex-wrap gap-x-5 gap-y-3">
          <UCheckbox
            v-for="t in TRIGGERS"
            :key="t.key"
            :model-value="isTriggerSelected(t.key)"
            :label="t.label"
            class="min-h-11 items-center"
            @update:model-value="(v) => toggleTrigger(t.key, v === true)"
          >
            <template v-if="t.recommended" #description>
              <UBadge color="success" variant="subtle" size="sm" label="recommended" />
            </template>
          </UCheckbox>
        </div>
      </div>

      <UButton :loading="syncing" label="Sync to Tautulli" class="min-h-11" @click="runSync" />

      <!-- Old design: a collapsible is a card whose header *is* the toggle, with
           a chevron that rotates open — not a bare text button on the page. -->
      <UCard :ui="{ body: 'p-0 sm:p-0' }" class="mt-4">
        <UCollapsible v-model:open="manual">
          <UButton color="neutral" variant="ghost" class="w-full min-h-11 gap-2.5 px-5 py-3.5">
            <UIcon
              name="i-lucide-chevron-right"
              class="size-4 shrink-0 text-muted transition-transform"
              :class="manual ? 'rotate-90' : ''"
            />
            <span class="text-sm font-semibold text-highlighted">Set it up manually instead</span>
          </UButton>
          <template #content>
            <div class="space-y-4 border-t border-default p-5">
              <CopyField label="Webhook URL" :value="webhookUrl" />
              <CopyField label="Method" value="POST" />
              <CopyField label="Headers" :value="'{&quot;Content-Type&quot;: &quot;application/json&quot;}'" />
              <CopyField
                label="JSON body"
                :value="'{&quot;action&quot;: &quot;{action}&quot;, &quot;rating_key&quot;: &quot;{rating_key}&quot;, &quot;username&quot;: &quot;{username}&quot;}'"
                hint="Paste into a Tautulli Webhook agent for each trigger you enable."
              />
            </div>
          </template>
        </UCollapsible>
      </UCard>
    </SetupStep>

    <DisclosureCard v-model:open="advanced" title="Advanced" summary="forwarding · seenr URL · bridge URL">
      <div class="flex items-center justify-between gap-3">
        <div class="min-w-0">
          <div class="text-sm font-medium">Forward to seenr</div>
          <p class="text-xs text-muted">Master switch for all forwarding.</p>
        </div>
        <USwitch v-model="store.settings.forward_enabled" />
      </div>
      <UFormField label="seenr base URL" help="each user's token is appended to this">
        <UInput v-model="store.settings.seenr_base_url" class="w-full" />
      </UFormField>
      <UFormField label="Bridge public URL" help="blank = auto-detect; set only behind a reverse proxy">
        <UInput v-model="store.settings.bridge_url" placeholder="https://bridge.example.com" class="w-full" />
      </UFormField>
      <UButton label="Save" class="min-h-11" @click="saveAdvanced" />
    </DisclosureCard>

    <DisclosureCard v-model:open="testPanel" title="Test a scrobble" summary="send a rating_key through the pipeline">
            <p class="text-xs text-muted">
              Runs a <code class="text-default">rating_key</code> through the same pipeline as a
              real Tautulli webhook — useful for checking id matching without waiting for playback.
            </p>

            <!-- items-start (not items-end): the username field's help text
                 below its input makes that cell taller than its siblings, so
                 bottom-aligning would misalign the inputs. -->
            <div class="grid gap-3 sm:grid-cols-3 sm:items-start">
              <UFormField label="rating_key">
                <UInput v-model="testRatingKey" placeholder="25419" class="w-full" />
              </UFormField>
              <UFormField label="username" help="must have a seenr token mapped above">
                <USelectMenu
                  v-model="testUsername"
                  :items="mappedUsernames"
                  create-item
                  placeholder="Select or type…"
                  class="w-full"
                  @create="(item) => { testUsername = item }"
                />
              </UFormField>
              <UFormField label="action">
                <USelectMenu v-model="testAction" :items="TEST_ACTIONS" class="w-full" />
              </UFormField>
            </div>

            <div class="space-y-2">
              <p class="text-xs text-muted">
                <strong class="text-default">Preview</strong> only builds the payload — nothing is
                sent and nothing is recorded.
                <strong class="text-default">Send to seenr for real</strong> actually forwards it
                to this user's seenr account and writes an event row.
              </p>
              <div class="flex flex-wrap gap-3">
                <UButton
                  color="neutral"
                  variant="outline"
                  icon="i-lucide-eye"
                  label="Preview"
                  class="min-h-11"
                  :loading="previewBusy"
                  :disabled="sendBusy"
                  @click="runTest(true)"
                />
                <!-- error (rose), not warning (amber): this is the destructive
                     half of the pair, and amber is not in this palette. -->
                <UButton
                  color="error"
                  icon="i-lucide-send"
                  label="Send to seenr for real"
                  class="min-h-11"
                  :loading="sendBusy"
                  :disabled="previewBusy"
                  @click="runTest(false)"
                />
              </div>
            </div>

            <div v-if="testResult" class="space-y-3 border-t border-default pt-4">
              <div class="flex flex-wrap items-center gap-2">
                <UBadge
                  :color="testResult.ok ? 'success' : testResult.skipped ? 'warning' : 'error'"
                  variant="subtle"
                  :label="testResult.ok ? 'ok' : testResult.skipped ? 'skipped' : 'failed'"
                />
                <UBadge
                  v-if="testResult.media_type"
                  color="neutral"
                  variant="subtle"
                  :label="testResult.media_type"
                />
                <UBadge
                  v-if="testResult.seenr_status"
                  color="neutral"
                  variant="subtle"
                  :label="`seenr ${testResult.seenr_status}`"
                />
              </div>

              <div v-if="testResult.title" class="text-sm font-medium">{{ testResult.title }}</div>
              <div v-if="testResult.ids?.length" class="text-xs text-dimmed">
                ids: {{ testResult.ids.join(', ') }}
              </div>

              <UAlert
                v-if="testResult.reason"
                :color="testResult.ok ? 'neutral' : testResult.skipped ? 'warning' : 'error'"
                variant="subtle"
                :description="testResult.reason"
              />

              <pre
                v-if="testResult.payload"
                class="max-h-64 overflow-auto rounded-lg bg-default p-3 text-xs ring-1 ring-default"
              >{{ testResultPayload }}</pre>
            </div>
    </DisclosureCard>

    <UModal
      :open="!!edit"
      :title="edit ? `Configure ${edit.username}` : ''"
      @update:open="(v) => { if (!v) edit = null }"
    >
      <template #body>
        <div v-if="edit" class="space-y-4">
          <UFormField label="seenr token">
            <UInput v-model="edit.seenr_token" class="w-full" />
          </UFormField>
          <div class="flex items-center justify-between gap-3">
            <span class="text-sm">Enabled</span>
            <USwitch v-model="edit.enabled" />
          </div>
          <div class="flex items-center justify-between gap-3">
            <span class="text-sm">TV episodes</span>
            <USwitch v-model="edit.sync_episodes" />
          </div>
          <div class="flex items-center justify-between gap-3">
            <span class="text-sm">Movies</span>
            <USwitch v-model="edit.sync_movies" />
          </div>
        </div>
      </template>
      <template #footer>
        <div class="flex w-full flex-wrap justify-between gap-3">
          <UButton color="error" variant="ghost" label="Remove" class="min-h-11" @click="removeEdit" />
          <div class="flex gap-3">
            <UButton color="neutral" variant="subtle" label="Cancel" class="min-h-11" @click="edit = null" />
            <UButton label="Save" class="min-h-11" @click="saveEdit" />
          </div>
        </div>
      </template>
    </UModal>
  </div>
</template>

// client/src/pages/Settings.tsx
import { useEffect, useState, type ReactNode } from 'react';
import { api } from '../api';
import type { Settings as TSettings, Mapping, TestResult, SyncResult, Status } from '../types';
import { Button, Field, Input, Toggle, Badge, CopyField, Modal } from '../components/ui';

function syncSummary(m: { sync_episodes: boolean; sync_movies: boolean }): string {
  if (m.sync_episodes && m.sync_movies) return 'TV + Movies';
  if (m.sync_episodes) return 'TV only';
  if (m.sync_movies) return 'Movies only';
  return 'nothing';
}

const TRIGGERS = [
  { key: 'watched', label: 'Watched', recommended: true },
  { key: 'play', label: 'Play' },
  { key: 'stop', label: 'Stop' },
  { key: 'pause', label: 'Pause' },
  { key: 'resume', label: 'Resume' },
];

function Step({ n, title, hint, children }: { n: number; title: string; hint?: string; children: ReactNode }) {
  return (
    <div className="rounded-2xl border border-white/10 bg-white/[0.02]">
      <div className="flex items-center gap-3 border-b border-white/10 px-5 py-3.5">
        <span className="grid h-6 w-6 shrink-0 place-items-center rounded-full bg-violet-600 text-xs font-semibold text-white">{n}</span>
        <span className="text-sm font-semibold text-white">{title}</span>
        {hint && <span className="ml-auto hidden text-xs text-slate-500 sm:block">{hint}</span>}
      </div>
      <div className="p-5">{children}</div>
    </div>
  );
}

function Collapsible({ open, onToggle, title, hint, children }: { open: boolean; onToggle: () => void; title: string; hint?: string; children: ReactNode }) {
  return (
    <div className="rounded-2xl border border-white/10 bg-white/[0.02]">
      <button onClick={onToggle} className="flex w-full items-center gap-2.5 px-5 py-3.5 text-left">
        <svg className={`h-4 w-4 shrink-0 text-slate-400 transition-transform ${open ? 'rotate-90' : ''}`} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="m9 18 6-6-6-6" /></svg>
        <span className="text-sm font-semibold text-white">{title}</span>
        {hint && <span className="ml-auto hidden text-xs text-slate-500 sm:block">{hint}</span>}
      </button>
      {open && <div className="border-t border-white/10 p-5">{children}</div>}
    </div>
  );
}

function Dot({ ok }: { ok: boolean | null }) {
  return <span className={`h-1.5 w-1.5 rounded-full ${ok === null ? 'bg-slate-500' : ok ? 'bg-emerald-500' : 'bg-rose-500'}`} />;
}

export default function Settings() {
  const [s, setS] = useState<TSettings | null>(null);
  const [saving, setSaving] = useState(false);
  const [saved, setSaved] = useState(false);
  const [status, setStatus] = useState<Status | null>(null);
  const [testMsg, setTestMsg] = useState<{ ok: boolean; message: string } | null>(null);

  const [mappings, setMappings] = useState<Mapping[]>([]);
  const [newUser, setNewUser] = useState('');
  const [newToken, setNewToken] = useState('');
  const [edit, setEdit] = useState<Mapping | null>(null);

  const [testRk, setTestRk] = useState('');
  const [testUser, setTestUser] = useState('');
  const [testAction, setTestAction] = useState('watched');
  const [testResult, setTestResult] = useState<TestResult | null>(null);
  const [testBusy, setTestBusy] = useState(false);

  const [syncing, setSyncing] = useState(false);
  const [syncResult, setSyncResult] = useState<SyncResult | null>(null);
  const [triggers, setTriggers] = useState<Record<string, boolean>>({ watched: true, play: false, stop: false, pause: false, resume: false });

  const [showManual, setShowManual] = useState(false);
  const [showAdvanced, setShowAdvanced] = useState(false);
  const [showTest, setShowTest] = useState(false);

  const refreshStatus = () => api.getStatus().then(setStatus).catch(() => setStatus(null));

  useEffect(() => {
    api.getSettings().then(setS);
    api.getMappings().then(setMappings);
    refreshStatus();
  }, []);

  const save = async () => {
    if (!s) return;
    setSaving(true);
    try {
      setS(await api.saveSettings(s));
      setSaved(true);
      setTimeout(() => setSaved(false), 2000);
      refreshStatus();
    } finally {
      setSaving(false);
    }
  };

  // instant-apply for toggles
  const patch = async (p: Partial<TSettings>) => {
    if (!s) return;
    const next = { ...s, ...p };
    setS(next);
    await api.saveSettings(next);
  };

  const testConn = async () => {
    if (!s) return;
    setTestMsg(null);
    setTestMsg(await api.testTautulli({ tautulli_url: s.tautulli_url, tautulli_apikey: s.tautulli_apikey }));
    refreshStatus();
  };

  const addMapping = async () => {
    if (!newUser.trim() || !newToken.trim()) return;
    await api.saveMapping({ username: newUser.trim(), seenr_token: newToken.trim(), enabled: true });
    setNewUser('');
    setNewToken('');
    setMappings(await api.getMappings());
    refreshStatus();
  };
  const delMapping = async (id: number) => {
    await api.deleteMapping(id);
    setMappings(await api.getMappings());
    refreshStatus();
  };
  const saveEdit = async () => {
    if (!edit) return;
    await api.saveMapping({
      username: edit.username,
      seenr_token: edit.seenr_token.trim(),
      enabled: edit.enabled,
      sync_movies: edit.sync_movies,
      sync_episodes: edit.sync_episodes,
    });
    setEdit(null);
    setMappings(await api.getMappings());
    refreshStatus();
  };

  const runTest = async (dryRun: boolean) => {
    if (!testRk.trim() || !testUser.trim()) return;
    setTestBusy(true);
    setTestResult(null);
    try {
      setTestResult(await api.test({ rating_key: testRk.trim(), username: testUser.trim(), action: testAction, dryRun }));
    } catch (e: any) {
      setTestResult({ ok: false, reason: e.message });
    } finally {
      setTestBusy(false);
    }
  };

  const runSync = async () => {
    setSyncing(true);
    setSyncResult(null);
    try {
      setSyncResult(await api.syncWebhook(Object.keys(triggers).filter((k) => triggers[k])));
      refreshStatus();
    } catch (e: any) {
      setSyncResult({ ok: false, error: e.message });
    } finally {
      setSyncing(false);
    }
  };

  if (!s) return <div className="text-slate-400">Loading…</div>;

  const webhookUrl = `${(s.bridge_url || window.location.origin).replace(/\/+$/, '')}/api/webhook/tautulli`;

  return (
    <div className="space-y-4">
      <div className="flex flex-wrap items-center justify-between gap-3">
        <h1 className="text-lg font-semibold text-white">Setup</h1>
        <div className="flex flex-wrap items-center gap-x-4 gap-y-1 text-xs">
          <span className="flex items-center gap-1.5"><Dot ok={status ? status.tautulli.ok : null} /><span className="text-slate-400">{status ? (status.tautulli.ok ? 'Tautulli connected' : 'Tautulli offline') : 'checking…'}</span></span>
          <span className="text-slate-500">{status?.users ?? '—'} {status?.users === 1 ? 'user' : 'users'}</span>
          <span className="flex items-center gap-1.5"><Dot ok={status ? status.webhook : null} /><span className="text-slate-400">{status ? (status.webhook ? 'webhook active' : 'no webhook') : ''}</span></span>
        </div>
      </div>

      <Step n={1} title="Connect Tautulli" hint="where the bridge reads episode IDs">
        <div className="grid gap-4 sm:grid-cols-2">
          <Field label="Tautulli URL" hint="e.g. http://tautulli:8181">
            <Input value={s.tautulli_url} onChange={(e) => setS({ ...s, tautulli_url: e.target.value })} placeholder="http://tautulli:8181" />
          </Field>
          <Field label="API key" hint="Tautulli → Settings → Web Interface → API key">
            <Input value={s.tautulli_apikey} onChange={(e) => setS({ ...s, tautulli_apikey: e.target.value })} placeholder="xxxxxxxx" type="password" />
          </Field>
        </div>
        <div className="mt-4 flex flex-wrap items-center gap-3">
          <Button variant="ghost" onClick={testConn}>Test connection</Button>
          <Button onClick={save} disabled={saving}>{saving ? 'Saving…' : 'Save'}</Button>
          {saved && <Badge tone="green">saved</Badge>}
          {testMsg && <Badge tone={testMsg.ok ? 'green' : 'red'}>{testMsg.message}</Badge>}
        </div>
      </Step>

      <Step n={2} title="Map users to seenr" hint="each Plex user → their seenr token">
        <div className="space-y-2">
          {mappings.length === 0 && <div className="py-1 text-sm text-slate-500">No users yet. Add one below.</div>}
          {mappings.map((m) => (
            <div key={m.id} className="flex items-center gap-3 rounded-lg border border-white/10 bg-black/20 px-3 py-2.5">
              <div className="min-w-0 flex-1">
                <div className="flex items-center gap-2 text-sm font-medium text-white">
                  <span className="truncate">{m.username}</span>
                  {!m.enabled && <span className="rounded-full bg-slate-500/15 px-2 py-0.5 text-[10px] font-medium text-slate-400 ring-1 ring-inset ring-slate-500/30">paused</span>}
                </div>
                <div className="mt-0.5 flex items-center gap-2 text-xs text-slate-500">
                  <span className="font-mono">{m.seenr_token.slice(0, 8)}…{m.seenr_token.slice(-6)}</span>
                  <span>·</span>
                  <span>{syncSummary(m)}</span>
                </div>
              </div>
              <Button variant="ghost" onClick={() => setEdit({ ...m })}>Configure</Button>
            </div>
          ))}
        </div>
        <div className="mt-4 grid gap-3 sm:grid-cols-[1fr_2fr_auto] sm:items-start">
          <Field label="Plex username"><Input value={newUser} onChange={(e) => setNewUser(e.target.value)} placeholder="plexuser" /></Field>
          <Field label="seenr token" hint="the part after /scrobble/plex/ in your seenr URL">
            <Input value={newToken} onChange={(e) => setNewToken(e.target.value)} placeholder="9%7CyourSeenrToken" />
          </Field>
          <div>
            <div className="mb-1.5 select-none text-sm" aria-hidden>&nbsp;</div>
            <Button onClick={addMapping}>Add</Button>
          </div>
        </div>
      </Step>

      <Step n={3} title="Send Tautulli's events here" hint="one webhook, covers every user">
        <div className="mb-4">
          <div className="mb-2.5 text-sm font-medium text-slate-200">Triggers to enable</div>
          <div className="flex flex-wrap gap-x-5 gap-y-2.5">
            {TRIGGERS.map((t) => (
              <label key={t.key} className="flex cursor-pointer items-center gap-2 text-sm text-slate-300">
                <input type="checkbox" checked={!!triggers[t.key]} onChange={() => setTriggers((p) => ({ ...p, [t.key]: !p[t.key] }))} className="h-4 w-4 accent-violet-500" />
                {t.label}
                {t.recommended && <span className="rounded-full bg-emerald-500/15 px-2 py-0.5 text-[10px] font-medium text-emerald-300 ring-1 ring-inset ring-emerald-500/30">recommended</span>}
              </label>
            ))}
          </div>
        </div>
        <div className="flex flex-wrap items-center gap-3">
          <Button onClick={runSync} disabled={syncing}>{syncing ? 'Syncing…' : 'Sync to Tautulli'}</Button>
          {syncResult && (
            <Badge tone={syncResult.ok ? 'green' : 'red'}>
              {syncResult.ok ? `${syncResult.created ? 'created' : 'updated'} webhook #${syncResult.notifier_id}` : syncResult.error || 'sync failed'}
            </Badge>
          )}
        </div>
        <p className="mt-2 text-xs text-slate-500">Creates or updates a “Seenr Bridge” webhook notifier in Tautulli with the triggers you pick. Watched is what marks items as watched in seenr.</p>

        <div className="mt-4">
          <Collapsible open={showManual} onToggle={() => setShowManual(!showManual)} title="Set it up manually instead">
            <div className="space-y-4">
              <CopyField label="Webhook URL   ·   Method: POST" value={webhookUrl} hint="Must be reachable from your Tautulli host/container." />
              <CopyField label="JSON Headers" value={'{"Content-Type": "application/json"}'} />
              <CopyField label="JSON Data   (paste into each trigger you enable)" value={'{"action": "{action}", "rating_key": "{rating_key}", "username": "{username}"}'} />
            </div>
          </Collapsible>
        </div>
      </Step>

      <Collapsible open={showAdvanced} onToggle={() => setShowAdvanced(!showAdvanced)} title="Advanced" hint="forwarding · seenr URL · bridge URL">
        <div className="space-y-5">
          <div className="flex items-center gap-3">
            <Toggle checked={s.forward_enabled} onChange={(v) => patch({ forward_enabled: v })} />
            <span className="text-sm text-slate-300">Forward to seenr{!s.forward_enabled && ' — paused'} <span className="text-slate-500">· master switch for all users</span></span>
          </div>

          <div className="grid gap-4 border-t border-white/10 pt-5 sm:grid-cols-2 sm:items-start">
            <Field label="seenr base URL" hint="token is appended per user; default is correct for seenr.app">
              <Input value={s.seenr_base_url} onChange={(e) => setS({ ...s, seenr_base_url: e.target.value })} />
            </Field>
            <Field label="Bridge public URL (optional)" hint="the URL Tautulli uses to reach the bridge; blank = auto-detect">
              <Input value={s.bridge_url} onChange={(e) => setS({ ...s, bridge_url: e.target.value })} placeholder="http://192.168.1.10:8687" />
            </Field>
          </div>
          <div className="flex items-center gap-3">
            <Button onClick={save} disabled={saving}>{saving ? 'Saving…' : 'Save'}</Button>
            {saved && <Badge tone="green">saved</Badge>}
          </div>
        </div>
      </Collapsible>

      <Collapsible open={showTest} onToggle={() => setShowTest(!showTest)} title="Test a scrobble" hint="send a rating_key through the pipeline">
        <div className="grid gap-3 sm:grid-cols-3 sm:items-end">
          <Field label="rating_key"><Input value={testRk} onChange={(e) => setTestRk(e.target.value)} placeholder="25419" /></Field>
          <Field label="username"><Input value={testUser} onChange={(e) => setTestUser(e.target.value)} placeholder="plexuser" /></Field>
          <Field label="action">
            <select value={testAction} onChange={(e) => setTestAction(e.target.value)} className="w-full rounded-lg border border-white/10 bg-black/30 px-3 py-2 text-sm text-white outline-none focus:border-violet-500/60">
              {['watched', 'play', 'pause', 'resume', 'stop'].map((a) => <option key={a} value={a}>{a}</option>)}
            </select>
          </Field>
        </div>
        <div className="mt-4 flex flex-wrap items-center gap-3">
          <Button variant="ghost" onClick={() => runTest(true)} disabled={testBusy}>Preview payload</Button>
          <Button onClick={() => runTest(false)} disabled={testBusy}>Send to seenr</Button>
          {testResult && (
            <Badge tone={testResult.ok ? 'green' : testResult.skipped ? 'amber' : 'red'}>
              {testResult.ok ? (testResult.seenr_status ? `sent · seenr ${testResult.seenr_status}` : 'payload built') : testResult.reason || 'failed'}
            </Badge>
          )}
        </div>
        {testResult?.payload && (
          <pre className="mt-3 max-h-72 overflow-auto rounded-lg bg-black/40 p-3 text-xs text-slate-300">
{JSON.stringify(testResult.payload, null, 2)}
          </pre>
        )}
      </Collapsible>

      <Modal
        open={!!edit}
        onClose={() => setEdit(null)}
        title={edit ? `Configure ${edit.username}` : ''}
        footer={
          <>
            <Button variant="ghost" onClick={() => setEdit(null)}>Cancel</Button>
            <Button onClick={saveEdit}>Save</Button>
          </>
        }
      >
        {edit && (
          <div className="space-y-4">
            <Field label="seenr token" hint="the part after /scrobble/plex/ in this user's seenr URL">
              <Input value={edit.seenr_token} onChange={(e) => setEdit({ ...edit, seenr_token: e.target.value })} />
            </Field>
            <label className="flex items-center gap-3">
              <Toggle checked={edit.enabled} onChange={(v) => setEdit({ ...edit, enabled: v })} />
              <span className="text-sm text-slate-300">Active{!edit.enabled && ' — paused'}</span>
            </label>
            <div className="border-t border-white/10 pt-4">
              <div className="mb-2.5 text-sm font-medium text-slate-200">What to sync</div>
              <div className="flex flex-col gap-2.5">
                <label className="flex items-center gap-3"><Toggle checked={edit.sync_episodes} onChange={(v) => setEdit({ ...edit, sync_episodes: v })} /><span className="text-sm text-slate-300">TV episodes</span></label>
                <label className="flex items-center gap-3"><Toggle checked={edit.sync_movies} onChange={(v) => setEdit({ ...edit, sync_movies: v })} /><span className="text-sm text-slate-300">Movies</span></label>
              </div>
            </div>
            <button onClick={() => { delMapping(edit.id); setEdit(null); }} className="text-xs text-rose-400 transition hover:text-rose-300">Remove this user</button>
          </div>
        )}
      </Modal>
    </div>
  );
}
