// app/pages/shared.vue
<script setup lang="ts">
import type { BackfillResult, LibraryItem, Mapping, SharedTitle } from '../../shared/types'
import { apiErrorMessage } from '../../shared/errors'

// /api/tautulli/library answers with ok:false (+ error) instead of throwing, so a
// Tautulli problem can be shown inline while the rest of the page keeps working.
// It's an endpoint-local envelope, not part of the shared wire contract.
interface LibraryPage {
  ok: boolean
  items: LibraryItem[]
  total: number
  error?: string
}

type MediaType = 'show' | 'movie'

interface BackfillMessage {
  ok: boolean
  msg: string
}

// One view-ready row, so the template never has to index the lookup maps
// (noUncheckedIndexedAccess makes that awkward) or rebuild poster URLs inline.
interface Row {
  rating_key: string
  media_type: string
  title: string | null
  year: string | null
  image: string | null
  poster: string | null
  isShow: boolean
  profiles: number[]
  isShared: boolean
  result: BackfillMessage | null
  onlyNew: boolean
}

const PAGE_SIZE = 50

const MEDIA_TYPES: { value: MediaType; label: string }[] = [
  { value: 'show', label: 'TV Shows' },
  { value: 'movie', label: 'Movies' },
]

const { data: shared, refresh: refreshShared } = await useAsyncData<SharedTitle[]>(
  'shared',
  () => $fetch('/api/shared'),
  { default: (): SharedTitle[] => [] },
)

const { data: mappings } = await useAsyncData<Mapping[]>(
  'mappings',
  () => $fetch('/api/mappings'),
  { default: (): Mapping[] => [] },
)

const type = ref<MediaType>('show')
const search = ref('')
const query = ref('') // the applied search — only changes on submit
const items = ref<LibraryItem[]>([])
const total = ref(0)
const loading = ref(false)
const libError = ref<string | null>(null)
const sharedOnly = ref(false)

// Only one backfill runs at a time, so a single key is enough to track it.
const busyKey = ref<string | null>(null)
const results = ref(new Map<string, BackfillMessage>())
// Shows where "Only new ones" was picked. Per-title, client-side, not persisted.
const onlyNew = ref(new Set<string>())

const sharedMap = computed(() => {
  const m = new Map<string, number[]>()
  for (const s of shared.value) m.set(s.rating_key, s.profiles)
  return m
})

async function load(start: number) {
  loading.value = true
  libError.value = null
  try {
    const r = await $fetch<LibraryPage>('/api/tautulli/library', {
      query: { type: type.value, search: query.value, start, length: PAGE_SIZE },
    })
    if (!r.ok) libError.value = r.error || 'Could not load library from Tautulli.'
    items.value = start === 0 ? r.items : [...items.value, ...r.items]
    total.value = r.total
  } catch (e) {
    libError.value = apiErrorMessage(e, 'Could not load library from Tautulli.')
  } finally {
    loading.value = false
  }
}

// (Re)load the library when the type or the applied search changes, and when
// leaving the shared-only view. Shared-only reads from the stored titles instead.
watch([type, query, sharedOnly], () => {
  if (sharedOnly.value) return
  void load(0)
}, { immediate: true })

function applySearch() {
  query.value = search.value.trim()
}

const rows = computed<Row[]>(() => {
  const base = sharedOnly.value
    ? shared.value.map((s) => ({
        rating_key: s.rating_key,
        media_type: s.media_type,
        title: s.title,
        year: s.year,
        image: s.image,
      }))
    : items.value.map((i) => ({
        rating_key: i.rating_key,
        media_type: i.media_type,
        title: i.title,
        year: i.year,
        image: i.image,
      }))

  return base.map((r) => {
    const profiles = sharedMap.value.get(r.rating_key) ?? []
    return {
      ...r,
      poster: r.image ? `/api/image?path=${encodeURIComponent(r.image)}` : null,
      isShow: r.media_type === 'show',
      profiles,
      isShared: profiles.length > 0,
      result: results.value.get(r.rating_key) ?? null,
      onlyNew: onlyNew.value.has(r.rating_key),
    }
  })
})

function initials(name: string) {
  return name.slice(0, 2).toUpperCase()
}

// Optimistic: the chip flips immediately, the PUT follows. A failed PUT re-reads
// /api/shared so the UI can't stay out of step with the database.
async function toggleProfile(row: Row, mappingId: number) {
  const next = row.profiles.includes(mappingId)
    ? row.profiles.filter((id) => id !== mappingId)
    : [...row.profiles, mappingId]

  const existing = shared.value.find((s) => s.rating_key === row.rating_key)
  const others = shared.value.filter((s) => s.rating_key !== row.rating_key)
  // No profiles left means the title is no longer shared at all.
  shared.value = next.length === 0
    ? others
    : [...others, {
        rating_key: row.rating_key,
        media_type: row.media_type,
        title: row.title ?? existing?.title ?? null,
        year: row.year ?? existing?.year ?? null,
        image: row.image ?? existing?.image ?? null,
        profiles: next,
      }]

  try {
    await $fetch<{ ok: boolean; profiles: number[] }>('/api/shared', {
      method: 'PUT',
      body: {
        rating_key: row.rating_key,
        media_type: row.media_type,
        title: row.title ?? undefined,
        year: row.year ?? undefined,
        image: row.image ?? undefined,
        profiles: next,
      },
    })
  } catch {
    await refreshShared()
  }
}

function plural(n: number, word: string) {
  return `${n} ${word}${n === 1 ? '' : 's'}`
}

function backfillMessage(r: BackfillResult) {
  if (!r.ok && r.reason) return r.reason
  const failed = r.fail_count ? `, ${r.fail_count} failed` : ''
  if (r.media_type === 'movie') {
    return `marked watched for ${plural(r.profiles, 'profile')} (${r.ok_count} ok${failed})`
  }
  return `${plural(r.items, 'episode')} → ${plural(r.profiles, 'profile')} · ${r.ok_count} ok${failed}`
}

async function backfill(ratingKey: string) {
  busyKey.value = ratingKey
  results.value.delete(ratingKey)
  try {
    const r = await $fetch<BackfillResult>(
      `/api/shared/${encodeURIComponent(ratingKey)}/backfill`,
      { method: 'POST' },
    )
    results.value.set(ratingKey, { ok: r.ok, msg: backfillMessage(r) })
  } catch (e) {
    results.value.set(ratingKey, { ok: false, msg: apiErrorMessage(e, 'Sync failed.') })
  } finally {
    busyKey.value = null
  }
}

function setOnlyNew(ratingKey: string, value: boolean) {
  if (value) onlyNew.value.add(ratingKey)
  else onlyNew.value.delete(ratingKey)
}
</script>

<template>
  <div class="space-y-4">
    <div class="flex flex-wrap items-center justify-between gap-3">
      <div>
        <h2 class="text-lg font-semibold">Shared / co-watched</h2>
        <p class="mt-0.5 text-sm text-muted">
          Pick titles you watch together. A watch from any assigned profile scrobbles to all of them.
        </p>
      </div>
      <UBadge
        v-if="mappings.length > 0 && shared.length > 0"
        color="primary"
        variant="subtle"
        :label="`${shared.length} shared`"
      />
    </div>

    <!-- Co-watching shares a watch between profiles, so it needs profiles first. -->
    <UCard v-if="!mappings.length" :ui="{ body: 'px-5 py-8 sm:px-5 sm:py-8' }">
      <p class="text-center text-sm text-muted">
        Add at least one user under
        <ULink to="/settings" class="text-default">Settings → Map users</ULink>
        first. Co-watching needs profiles to share to.
      </p>
    </UCard>

    <template v-else>
      <div class="flex flex-wrap items-center gap-3">
        <!-- UFieldGroup is v4's renamed UButtonGroup — it joins the two buttons
             into one segmented control. Note that an unknown component name here
             typechecks fine and simply renders nothing, so it has to be verified
             against .nuxt/components.d.ts rather than trusted. -->
        <UFieldGroup>
          <UButton
            v-for="t in MEDIA_TYPES"
            :key="t.value"
            :color="type === t.value ? 'primary' : 'neutral'"
            :variant="type === t.value ? 'solid' : 'outline'"
            :label="t.label"
            :disabled="sharedOnly"
            class="min-h-11"
            @click="type = t.value"
          />
        </UFieldGroup>

        <form v-if="!sharedOnly" class="flex flex-1 items-center gap-2" @submit.prevent="applySearch">
          <UInput
            v-model="search"
            :placeholder="`Search ${type === 'show' ? 'shows' : 'movies'}…`"
            class="min-w-0 flex-1"
          />
          <UButton type="submit" color="neutral" variant="ghost" label="Search" class="min-h-11" />
        </form>

        <!-- UCheckbox emits 'indeterminate' as well as booleans, so v-model on a
             plain boolean ref doesn't typecheck — same reason settings.vue takes
             the update event instead. -->
        <UCheckbox
          :model-value="sharedOnly"
          label="Shared only"
          class="ml-auto min-h-11 items-center"
          @update:model-value="(v) => { sharedOnly = v === true }"
        />
      </div>

      <UAlert
        v-if="libError && !sharedOnly"
        color="error"
        variant="subtle"
        :description="libError"
      />

      <div class="space-y-2">
        <UCard v-if="!rows.length && !loading" :ui="{ body: 'px-5 py-8 sm:px-5 sm:py-8' }">
          <p class="text-center text-sm text-muted">
            {{ sharedOnly
              ? 'Nothing shared yet. Turn off “Shared only” and pick titles to co-watch.'
              : 'No titles found.' }}
          </p>
        </UCard>

        <UCard
          v-for="row in rows"
          :key="row.rating_key"
          :ui="{ body: 'p-3 sm:p-3' }"
          :class="row.isShared ? 'bg-primary/5 ring-primary/25' : ''"
        >
          <div class="flex gap-3">
            <img
              v-if="row.poster"
              :src="row.poster"
              alt=""
              loading="lazy"
              class="h-[72px] w-12 shrink-0 rounded-md object-cover ring-1 ring-default"
            >
            <div v-else class="h-[72px] w-12 shrink-0 rounded-md bg-elevated ring-1 ring-default" />

            <div class="min-w-0 flex-1">
              <div class="flex flex-wrap items-center gap-2">
                <span class="min-w-0 truncate text-sm font-medium">{{ row.title }}</span>
                <span v-if="row.year" class="text-xs text-dimmed">{{ row.year }}</span>
                <UBadge
                  :color="row.isShow ? 'primary' : 'info'"
                  variant="subtle"
                  size="sm"
                  :label="row.isShow ? 'show' : 'movie'"
                />
              </div>

              <div class="mt-2 flex flex-wrap gap-1.5">
                <UButton
                  v-for="m in mappings"
                  :key="m.id"
                  :color="row.profiles.includes(m.id) ? 'primary' : 'neutral'"
                  :variant="row.profiles.includes(m.id) ? 'solid' : 'subtle'"
                  size="sm"
                  :title="m.username"
                  :label="m.username"
                  class="min-h-9 rounded-full"
                  @click="toggleProfile(row, m.id)"
                >
                  <template #leading>
                    <UAvatar
                      :text="initials(m.username)"
                      size="3xs"
                      :ui="{ root: 'bg-inverted/15', fallback: 'text-inherit text-[9px]' }"
                    />
                  </template>
                </UButton>
              </div>

              <!-- Retroactive sync: only meaningful once someone is assigned. -->
              <div v-if="row.isShared" class="mt-2.5 flex flex-wrap items-center gap-2">
                <template v-if="row.isShow">
                  <span v-if="row.onlyNew" class="text-xs text-muted">
                    Only new watches will sync.
                    <ULink class="text-primary" @click="setOnlyNew(row.rating_key, false)">change</ULink>
                  </span>
                  <template v-else>
                    <UButton
                      color="neutral"
                      variant="outline"
                      label="Sync all previous episodes"
                      class="min-h-11"
                      :loading="busyKey === row.rating_key"
                      :disabled="busyKey !== null && busyKey !== row.rating_key"
                      @click="backfill(row.rating_key)"
                    />
                    <UButton
                      color="neutral"
                      variant="ghost"
                      label="Only new ones"
                      class="min-h-11"
                      @click="setOnlyNew(row.rating_key, true)"
                    />
                  </template>
                </template>
                <UButton
                  v-else
                  color="neutral"
                  variant="outline"
                  label="Sync now"
                  class="min-h-11"
                  :loading="busyKey === row.rating_key"
                  :disabled="busyKey !== null && busyKey !== row.rating_key"
                  @click="backfill(row.rating_key)"
                />

                <UBadge
                  v-if="row.result"
                  :color="row.result.ok ? 'success' : 'error'"
                  variant="subtle"
                  :label="row.result.msg"
                />
              </div>
            </div>
          </div>
        </UCard>
      </div>

      <div v-if="!sharedOnly && items.length < total" class="pt-1 text-center">
        <UButton
          color="neutral"
          variant="ghost"
          class="min-h-11"
          :loading="loading"
          :label="`Load more (${items.length}/${total})`"
          @click="load(items.length)"
        />
      </div>

      <div v-if="loading && !items.length" class="py-6 text-center text-sm text-muted">
        Loading library…
      </div>
    </template>
  </div>
</template>

// client/src/pages/Shared.tsx
import { useEffect, useMemo, useState } from 'react';
import { api } from '../api';
import type { LibraryItem, SharedTitle, Mapping, BackfillResult } from '../types';
import { Button, Badge } from '../components/ui';

type MediaType = 'show' | 'movie';

function poster(path: string | null | undefined) {
  return path ? `/api/image?path=${encodeURIComponent(path)}` : null;
}

export default function Shared() {
  const [type, setType] = useState<MediaType>('show');
  const [search, setSearch] = useState('');
  const [query, setQuery] = useState(''); // debounced/applied search
  const [items, setItems] = useState<LibraryItem[]>([]);
  const [total, setTotal] = useState(0);
  const [loading, setLoading] = useState(false);
  const [libError, setLibError] = useState<string | null>(null);
  const [sharedOnly, setSharedOnly] = useState(false);

  const [shared, setShared] = useState<SharedTitle[]>([]);
  const [mappings, setMappings] = useState<Mapping[]>([]);

  const [busyKey, setBusyKey] = useState<string | null>(null);
  const [result, setResult] = useState<Record<string, { ok: boolean; msg: string }>>({});
  const [dismissed, setDismissed] = useState<Record<string, boolean>>({}); // shows: "only new ones" chosen

  const sharedMap = useMemo(() => {
    const m = new Map<string, number[]>();
    for (const s of shared) m.set(s.rating_key, s.profiles);
    return m;
  }, [shared]);

  useEffect(() => {
    api.getShared().then(setShared).catch(() => setShared([]));
    api.getMappings().then(setMappings).catch(() => setMappings([]));
  }, []);

  const load = (t: MediaType, q: string, start: number) => {
    setLoading(true);
    setLibError(null);
    api
      .getLibrary(t, q, start, 50)
      .then((r) => {
        if (!r.ok) setLibError(r.error || 'Could not load library from Tautulli.');
        setItems((prev) => (start === 0 ? r.items : [...prev, ...r.items]));
        setTotal(r.total);
      })
      .catch((e) => setLibError(e.message))
      .finally(() => setLoading(false));
  };

  // (re)load list when type or applied query changes, unless we're in shared-only view
  useEffect(() => {
    if (sharedOnly) return;
    load(type, query, 0);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [type, query, sharedOnly]);

  const applySearch = () => setQuery(search.trim());

  const toggleProfile = async (item: { rating_key: string; media_type: string; title?: string | null; year?: string | null; image?: string | null }, mappingId: number) => {
    const cur = sharedMap.get(item.rating_key) || [];
    const next = cur.includes(mappingId) ? cur.filter((id) => id !== mappingId) : [...cur, mappingId];
    // optimistic
    setShared((prev) => {
      const others = prev.filter((s) => s.rating_key !== item.rating_key);
      if (next.length === 0) return others;
      const existing = prev.find((s) => s.rating_key === item.rating_key);
      return [
        ...others,
        {
          rating_key: item.rating_key,
          media_type: item.media_type,
          title: item.title ?? existing?.title ?? null,
          year: item.year ?? existing?.year ?? null,
          image: item.image ?? existing?.image ?? null,
          profiles: next,
        },
      ];
    });
    try {
      await api.setShared({
        rating_key: item.rating_key,
        media_type: item.media_type,
        title: item.title ?? undefined,
        year: item.year ?? undefined,
        image: item.image ?? undefined,
        profiles: next,
      });
    } catch {
      api.getShared().then(setShared).catch(() => {});
    }
  };

  const backfill = async (rating_key: string) => {
    setBusyKey(rating_key);
    setResult((r) => ({ ...r, [rating_key]: undefined as any }));
    try {
      const r: BackfillResult = await api.backfillShared(rating_key);
      let msg: string;
      if (!r.ok && r.reason) msg = r.reason;
      else if (r.media_type === 'movie') msg = `marked watched for ${r.profiles} profile${r.profiles === 1 ? '' : 's'} (${r.ok_count} ok${r.fail_count ? `, ${r.fail_count} failed` : ''})`;
      else msg = `${r.items} episode${r.items === 1 ? '' : 's'} → ${r.profiles} profile${r.profiles === 1 ? '' : 's'} · ${r.ok_count} ok${r.fail_count ? `, ${r.fail_count} failed` : ''}`;
      setResult((res) => ({ ...res, [rating_key]: { ok: r.ok, msg } }));
    } catch (e: any) {
      setResult((res) => ({ ...res, [rating_key]: { ok: false, msg: e.message } }));
    } finally {
      setBusyKey(null);
    }
  };

  const initials = (name: string) => name.slice(0, 2).toUpperCase();

  // Rows to render: the library page, or (shared-only) the stored shared titles.
  const rows: { rating_key: string; media_type: string; title: string | null; year: string | null; image: string | null }[] = sharedOnly
    ? shared.map((s) => ({ rating_key: s.rating_key, media_type: s.media_type, title: s.title, year: s.year, image: s.image }))
    : items.map((i) => ({ rating_key: i.rating_key, media_type: i.media_type, title: i.title, year: i.year, image: i.image }));

  if (mappings.length === 0) {
    return (
      <div className="space-y-4">
        <Header />
        <div className="rounded-2xl border border-white/10 bg-white/[0.02] px-5 py-8 text-center text-sm text-slate-400">
          Add at least one user under <span className="text-slate-200">Settings → Map users</span> first. Co-watching needs profiles to share to.
        </div>
      </div>
    );
  }

  return (
    <div className="space-y-4">
      <Header count={shared.length} />

      <div className="flex flex-wrap items-center gap-3">
        <div className="inline-flex rounded-lg border border-white/10 bg-black/20 p-0.5">
          {(['show', 'movie'] as MediaType[]).map((t) => (
            <button
              key={t}
              onClick={() => setType(t)}
              disabled={sharedOnly}
              className={`rounded-md px-3 py-1.5 text-sm font-medium transition disabled:opacity-40 ${type === t ? 'bg-violet-600 text-white' : 'text-slate-400 hover:text-white'}`}
            >
              {t === 'show' ? 'TV Shows' : 'Movies'}
            </button>
          ))}
        </div>

        {!sharedOnly && (
          <div className="flex flex-1 items-center gap-2">
            <input
              value={search}
              onChange={(e) => setSearch(e.target.value)}
              onKeyDown={(e) => e.key === 'Enter' && applySearch()}
              placeholder={`Search ${type === 'show' ? 'shows' : 'movies'}…`}
              className="min-w-0 flex-1 rounded-lg border border-white/10 bg-black/30 px-3 py-2 text-sm text-white placeholder:text-slate-500 outline-none focus:border-violet-500/60"
            />
            <Button variant="ghost" onClick={applySearch}>Search</Button>
          </div>
        )}

        <label className="ml-auto flex cursor-pointer items-center gap-2 text-sm text-slate-300">
          <input type="checkbox" checked={sharedOnly} onChange={(e) => setSharedOnly(e.target.checked)} className="h-4 w-4 accent-violet-500" />
          Shared only
        </label>
      </div>

      {libError && !sharedOnly && <div className="rounded-lg bg-rose-500/10 px-3 py-2 text-sm text-rose-300">{libError}</div>}

      <div className="space-y-2">
        {rows.length === 0 && !loading && (
          <div className="rounded-2xl border border-white/10 bg-white/[0.02] px-5 py-8 text-center text-sm text-slate-500">
            {sharedOnly ? 'Nothing shared yet. Turn off “Shared only” and pick titles to co-watch.' : 'No titles found.'}
          </div>
        )}

        {rows.map((item) => {
          const profiles = sharedMap.get(item.rating_key) || [];
          const isShared = profiles.length > 0;
          const isShow = item.media_type === 'show';
          const res = result[item.rating_key];
          return (
            <div key={item.rating_key} className={`rounded-xl border px-3 py-3 transition ${isShared ? 'border-violet-500/30 bg-violet-500/[0.06]' : 'border-white/10 bg-black/20'}`}>
              <div className="flex gap-3">
                <div className="h-[72px] w-12 shrink-0 overflow-hidden rounded-md bg-black/40">
                  {poster(item.image) ? <img src={poster(item.image)!} alt="" className="h-full w-full object-cover" /> : null}
                </div>
                <div className="min-w-0 flex-1">
                  <div className="flex items-center gap-2">
                    <span className="truncate text-sm font-medium text-white">{item.title}</span>
                    {item.year && <span className="text-xs text-slate-500">{item.year}</span>}
                    <span className={`rounded-full px-2 py-0.5 text-[10px] font-medium ring-1 ring-inset ${isShow ? 'bg-violet-500/15 text-violet-300 ring-violet-500/30' : 'bg-sky-500/15 text-sky-300 ring-sky-500/30'}`}>
                      {isShow ? 'show' : 'movie'}
                    </span>
                  </div>

                  {/* profile chips */}
                  <div className="mt-2 flex flex-wrap gap-1.5">
                    {mappings.map((m) => {
                      const on = profiles.includes(m.id);
                      return (
                        <button
                          key={m.id}
                          onClick={() => toggleProfile(item, m.id)}
                          title={m.username}
                          className={`inline-flex items-center gap-1.5 rounded-full px-2.5 py-1 text-xs font-medium transition ${on ? 'bg-violet-600 text-white' : 'bg-white/5 text-slate-400 ring-1 ring-inset ring-white/10 hover:text-white'}`}
                        >
                          <span className={`grid h-4 w-4 place-items-center rounded-full text-[9px] ${on ? 'bg-white/20' : 'bg-white/10'}`}>{initials(m.username)}</span>
                          {m.username}
                        </button>
                      );
                    })}
                  </div>

                  {/* retroactive actions when shared */}
                  {isShared && (
                    <div className="mt-2.5 flex flex-wrap items-center gap-2">
                      {isShow ? (
                        dismissed[item.rating_key] ? (
                          <span className="text-xs text-slate-500">Only new watches will sync. <button onClick={() => setDismissed((d) => ({ ...d, [item.rating_key]: false }))} className="text-violet-400 hover:text-violet-300">change</button></span>
                        ) : (
                          <>
                            <Button variant="ghost" onClick={() => backfill(item.rating_key)} disabled={busyKey === item.rating_key}>
                              {busyKey === item.rating_key ? 'Syncing…' : 'Sync all previous episodes'}
                            </Button>
                            <Button variant="ghost" onClick={() => setDismissed((d) => ({ ...d, [item.rating_key]: true }))}>Only new ones</Button>
                          </>
                        )
                      ) : (
                        <Button variant="ghost" onClick={() => backfill(item.rating_key)} disabled={busyKey === item.rating_key}>
                          {busyKey === item.rating_key ? 'Syncing…' : 'Sync now'}
                        </Button>
                      )}
                      {res && <Badge tone={res.ok ? 'green' : 'red'}>{res.msg}</Badge>}
                    </div>
                  )}
                </div>
              </div>
            </div>
          );
        })}
      </div>

      {!sharedOnly && items.length < total && (
        <div className="pt-1 text-center">
          <Button variant="ghost" onClick={() => load(type, query, items.length)} disabled={loading}>
            {loading ? 'Loading…' : `Load more (${items.length}/${total})`}
          </Button>
        </div>
      )}
      {loading && items.length === 0 && <div className="py-6 text-center text-sm text-slate-500">Loading library…</div>}
    </div>
  );
}

function Header({ count }: { count?: number }) {
  return (
    <div className="flex flex-wrap items-center justify-between gap-3">
      <div>
        <h1 className="text-lg font-semibold text-white">Shared / co-watched</h1>
        <p className="mt-0.5 text-sm text-slate-400">
          Pick titles you watch together. A watch from any assigned profile scrobbles to all of them.
        </p>
      </div>
      {count !== undefined && count > 0 && <Badge tone="violet">{count} shared</Badge>}
    </div>
  );
}
